use crate::database::models::MeetingSpeaker;
use crate::database::repositories::speaker::SpeakerRepository;
use crate::state::AppState;
use std::path::PathBuf;
use tauri::{AppHandle, Emitter, Manager};
use tracing::{error, info, warn};

use super::engine::{default_model_path, DiarizationEngine, SegmentInfo};

/// Run (or re-run) speaker diarization on a meeting's audio.
///
/// This runs on `tokio::task::spawn_blocking` so the UI thread is never blocked.
#[tauri::command]
pub async fn re_run_diarization(
    app: AppHandle,
    meeting_id: String,
    num_speakers: Option<u8>,
) -> Result<Vec<MeetingSpeaker>, String> {
    info!(
        "Diarization requested for meeting '{}', num_speakers={:?}",
        meeting_id, num_speakers
    );

    let state = app.state::<AppState>();
    let pool = state.db_manager.pool().clone();

    // 1. Get the meeting's folder path (where the WAV lives)
    let meeting = sqlx::query_as::<_, (String, Option<String>)>(
        "SELECT id, folder_path FROM meetings WHERE id = ?",
    )
    .bind(&meeting_id)
    .fetch_optional(&pool)
    .await
    .map_err(|e| {
        error!("Database error fetching meeting {}: {}", meeting_id, e);
        format!("Database error: {}", e)
    })?
    .ok_or_else(|| {
        error!("Meeting '{}' not found", meeting_id);
        format!("Meeting '{}' not found", meeting_id)
    })?;

    let folder_path = meeting.1.ok_or_else(|| {
        error!("Meeting {} has no folder path (no recording was saved)", meeting_id);
        "Meeting has no folder path (no recording was saved)".to_string()
    })?;

    // Find the audio file in the meeting folder
    let folder = PathBuf::from(&folder_path);
    let wav_path = find_audio_in_folder(&folder).map_err(|e| {
        error!("Failed to find audio file in {:?}: {}", folder, e);
        e
    })?;

    // 2. Load transcript segments with audio timing
    let segments: Vec<SegmentInfo> = sqlx::query_as::<_, (String, Option<f64>, Option<f64>)>(
        "SELECT id, audio_start_time, audio_end_time FROM transcripts WHERE meeting_id = ? AND audio_start_time IS NOT NULL ORDER BY audio_start_time ASC",
    )
    .bind(&meeting_id)
    .fetch_all(&pool)
    .await
    .map_err(|e| {
        error!("Failed to load transcript segments for meeting {}: {}", meeting_id, e);
        format!("Failed to load transcript segments: {}", e)
    })?
    .into_iter()
    .filter_map(|(id, start, end)| {
        match (start, end) {
            (Some(s), Some(e)) if e > s => Some(SegmentInfo {
                transcript_id: id,
                audio_start_time: s,
                audio_end_time: e,
            }),
            _ => None,
        }
    })
    .collect();

    if segments.is_empty() {
        error!("No transcript segments with audio timing found for meeting {}", meeting_id);
        return Err("No transcript segments with audio timing found".to_string());
    }

    info!("Found {} segments with audio timing", segments.len());

    // 3. Get model path
    let app_data_dir = app
        .path()
        .app_data_dir()
        .map_err(|e| {
            error!("Failed to get app data dir: {}", e);
            format!("Failed to get app data dir: {}", e)
        })?;
    let model_path = default_model_path(&app_data_dir);

    if !model_path.exists() {
        let msg = format!("Speaker embedding model not found at {:?}. Please download it first.", model_path);
        error!("{}", msg);
        return Err(msg);
    }

    // 4. Run diarization on a blocking thread
    let wav_path_clone = wav_path.clone();
    let diarization_result = tokio::task::spawn_blocking(move || {
        let mut engine = DiarizationEngine::new(&model_path).map_err(|e| {
            error!("Failed to initialize DiarizationEngine: {}", e);
            e
        })?;
        engine.diarize(&wav_path_clone, segments, num_speakers).map_err(|e| {
            error!("Diarization inference failed: {}", e);
            e
        })
    })
    .await
    .map_err(|e| {
        error!("Diarization task panicked: {}", e);
        format!("Diarization task panicked: {}", e)
    })?
    .map_err(|e| {
        error!("Diarization failed: {}", e);
        format!("Diarization failed: {}", e)
    })?;

    // 5. Save results to database
    let speakers_to_save: Vec<MeetingSpeaker> = diarization_result
        .speakers
        .iter()
        .map(|s| MeetingSpeaker {
            id: String::new(), // Will be generated by the repository
            meeting_id: meeting_id.clone(),
            internal_label: s.internal_label.clone(),
            custom_name: None,
            sample_start_time: s.sample_start_time,
            sample_end_time: s.sample_end_time,
            segment_count: s.segment_count as i64,
            created_at: String::new(), // Will be set by the repository
        })
        .collect();

    SpeakerRepository::save_speakers(&pool, &meeting_id, &speakers_to_save)
        .await
        .map_err(|e| {
            error!("Failed to save speakers for meeting {}: {}", meeting_id, e);
            format!("Failed to save speakers: {}", e)
        })?;

    SpeakerRepository::update_transcript_speaker_labels(&pool, &diarization_result.assignments)
        .await
        .map_err(|e| {
            error!("Failed to update transcript labels for meeting {}: {}", meeting_id, e);
            format!("Failed to update transcript labels: {}", e)
        })?;

    // 6. Emit event to frontend
    if let Err(e) = app.emit("diarization-complete", &meeting_id) {
        warn!("Failed to emit diarization-complete event: {}", e);
    }

    // 7. Return the saved speakers
    let saved_speakers = SpeakerRepository::get_speakers(&pool, &meeting_id)
        .await
        .map_err(|e| {
            error!("Failed to fetch speakers for meeting {}: {}", meeting_id, e);
            format!("Failed to fetch speakers: {}", e)
        })?;

    info!(
        "Diarization complete for meeting '{}': {} speakers",
        meeting_id,
        saved_speakers.len()
    );

    Ok(saved_speakers)
}

/// Get all identified speakers for a meeting.
#[tauri::command]
pub async fn get_speakers(
    app: AppHandle,
    meeting_id: String,
) -> Result<Vec<MeetingSpeaker>, String> {
    let state = app.state::<AppState>();
    let pool = state.db_manager.pool();

    SpeakerRepository::get_speakers(pool, &meeting_id)
        .await
        .map_err(|e| format!("Failed to get speakers: {}", e))
}

/// Update a speaker's custom display name.
#[tauri::command]
pub async fn update_speaker_name(
    app: AppHandle,
    meeting_id: String,
    internal_label: String,
    custom_name: String,
) -> Result<(), String> {
    let state = app.state::<AppState>();
    let pool = state.db_manager.pool();

    SpeakerRepository::update_speaker_name(pool, &meeting_id, &internal_label, &custom_name)
        .await
        .map_err(|e| format!("Failed to update speaker name: {}", e))?;

    // Emit event so the UI can refresh
    let _ = app.emit("speakers-updated", &meeting_id);

    Ok(())
}

/// Merge two speakers (label_b is absorbed into label_a).
#[tauri::command]
pub async fn merge_speakers(
    app: AppHandle,
    meeting_id: String,
    label_a: String,
    label_b: String,
) -> Result<Vec<MeetingSpeaker>, String> {
    let state = app.state::<AppState>();
    let pool = state.db_manager.pool();

    SpeakerRepository::merge_speakers(pool, &meeting_id, &label_a, &label_b)
        .await
        .map_err(|e| format!("Failed to merge speakers: {}", e))?;

    let _ = app.emit("speakers-updated", &meeting_id);

    SpeakerRepository::get_speakers(pool, &meeting_id)
        .await
        .map_err(|e| format!("Failed to get speakers after merge: {}", e))
}

/// Extract a short audio sample for a speaker and return it as WAV bytes.
/// The frontend plays this via Web Audio API.
#[tauri::command]
pub async fn play_speaker_sample(
    app: AppHandle,
    meeting_id: String,
    internal_label: String,
) -> Result<Vec<u8>, String> {
    let state = app.state::<AppState>();
    let pool = state.db_manager.pool();

    // Get the speaker's sample times
    let speaker = sqlx::query_as::<_, (f64, f64)>(
        "SELECT sample_start_time, sample_end_time FROM meeting_speakers WHERE meeting_id = ? AND internal_label = ?",
    )
    .bind(&meeting_id)
    .bind(&internal_label)
    .fetch_optional(pool)
    .await
    .map_err(|e| format!("Database error: {}", e))?
    .ok_or_else(|| format!("Speaker '{}' not found", internal_label))?;

    let (start_time, end_time) = speaker;

    // Get meeting folder path
    let folder_path: String = sqlx::query_scalar("SELECT folder_path FROM meetings WHERE id = ?")
        .bind(&meeting_id)
        .fetch_optional(pool)
        .await
        .map_err(|e| format!("Database error: {}", e))?
        .flatten()
        .ok_or_else(|| "Meeting has no folder path".to_string())?;

    let folder = PathBuf::from(&folder_path);
    let wav_path = find_audio_in_folder(&folder)?;

    // Extract the sample on a blocking thread
    let wav_bytes = tokio::task::spawn_blocking(move || {
        extract_audio_slice(&wav_path, start_time, end_time)
    })
    .await
    .map_err(|e| format!("Task panicked: {}", e))?
    .map_err(|e| format!("Failed to extract audio sample: {}", e))?;

    Ok(wav_bytes)
}

/// Find an audio file in the meeting folder.
fn find_audio_in_folder(folder: &PathBuf) -> Result<PathBuf, String> {
    if !folder.exists() {
        return Err(format!("Meeting folder not found: {:?}", folder));
    }

    // Try common naming conventions first
    let candidates = ["audio.mp4", "audio.m4a", "audio.wav", "audio.webm", "audio.mp3"];
    for cand in candidates.iter() {
        let path = folder.join(cand);
        if path.exists() {
            return Ok(path);
        }
    }

    // Fallback: search for any known extension
    let entries = std::fs::read_dir(folder)
        .map_err(|e| format!("Failed to read meeting folder: {}", e))?;

    for entry in entries {
        if let Ok(entry) = entry {
            let path = entry.path();
            if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if ["mp4", "m4a", "wav", "mp3", "webm", "ogg"].contains(&ext) {
                    return Ok(path);
                }
            }
        }
    }

    Err(format!("No audio file found in {:?}", folder))
}

/// Extract a time slice from an audio file and encode it as WAV bytes using FFmpeg.
fn extract_audio_slice(
    audio_path: &PathBuf,
    start_secs: f64,
    end_secs: f64,
) -> Result<Vec<u8>, String> {
    use crate::audio::ffmpeg::find_ffmpeg_path;

    let ffmpeg_path = find_ffmpeg_path().ok_or_else(|| "FFmpeg not found".to_string())?;
    let duration = end_secs - start_secs;

    let output = std::process::Command::new(ffmpeg_path)
        .arg("-y")
        .arg("-ss").arg(start_secs.to_string())
        .arg("-i").arg(audio_path)
        .arg("-t").arg(duration.to_string())
        .arg("-ar").arg("44100")
        .arg("-ac").arg("1")
        .arg("-c:a").arg("pcm_s16le")
        .arg("-f").arg("wav")
        .arg("pipe:1") // Stream WAV data to stdout
        .output()
        .map_err(|e| format!("Failed to execute ffmpeg: {}", e))?;

    if !output.status.success() {
        return Err(format!("FFmpeg failed to slice audio: {}", String::from_utf8_lossy(&output.stderr)));
    }

    Ok(output.stdout)
}
